# OpenRouteService configuration
# Get a free API key at: https://openrouteservice.org/dev/#/signup
ORS_BASE_URL=https://api.openrouteservice.org
ORS_API_KEY=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjYxMzA0NGU3MDZjZTQ5ODliZTU5NWMyMzIxMDk0ZWY4IiwiaCI6Im11cm11cjY0In0=
